import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

import {tracks} from './src/data/handbook';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const baseUrl = '/EngineeringHandbook/';

const config: Config = {
  title: 'Engineering Handbook',
  tagline: 'Short reference pages across the engineering stack',
  favicon: 'img/favicon.svg',

  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // GitHub Pages project site: https://kc3222.github.io/EngineeringHandbook/
  url: 'https://kc3222.github.io',
  baseUrl,
  organizationName: 'kc3222',
  projectName: 'EngineeringHandbook',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  headTags: [
    {
      tagName: 'link',
      attributes: {rel: 'preconnect', href: 'https://fonts.googleapis.com'},
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preconnect',
        href: 'https://fonts.gstatic.com',
        crossorigin: 'anonymous',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;800;900&family=JetBrains+Mono:wght@700&display=swap',
      },
    },
  ],

  presets: [
    [
      'classic',
      {
        // No content pages exist yet, so the docs and blog plugins are off.
        // When `content/` gets its first page files, turn docs back on with
        // `path: 'content'` and an autogenerated sidebar (see CLAUDE.md).
        docs: false,
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Engineering Handbook',
      // Rendered by src/theme/Navbar/Content — tracks sit centred, with the
      // search button and theme toggle pinned right.
      items: tracks.map((track) => ({
        to: track.permalink,
        label: track.navLabel,
        position: 'left' as const,
        activeBasePath: track.permalink,
      })),
    },
    footer: {
      copyright: `Engineering Handbook · ${new Date().getFullYear()}`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
