import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import {tracks, trackDir} from './src/data/handbook';

/**
 * One sidebar per track, each autogenerated from that track's `content/`
 * directory. Docusaurus shows the sidebar that contains the current doc, so
 * opening a page in another track swaps the whole sidebar — which is what makes
 * the track switcher in `src/components/TrackSwitcher` a real navigation
 * boundary rather than a filter.
 *
 * Sidebar ids are track slugs, so `useDocsSidebar().name` maps straight back to
 * `getTrack()`.
 */
const sidebars: SidebarsConfig = Object.fromEntries(
  tracks.map((track) => [
    track.slug,
    [{type: 'autogenerated' as const, dirName: trackDir(track)}],
  ]),
);

export default sidebars;
